### ISSUE TITLE
Templated catalog

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#1]
I believe we should make the identity module grab the catalog information from a config file similarly to how keystone represents their templated backend, for example: https://github.com/openstack/keystone/blob/master/etc/default_catalog.templates.

This would prevent the need to hard code anything and allow much more configurability to our simple identity imitation.

**Comment by beittenc** [comment]
Agreed. This should be easy enough to do using the driver.conf if we want.

**Comment by sudorandom** [comment]
This has been implemented in the latest commit. Some of the code is adopted from keystone for this.
