### ISSUE TITLE
Add ability to record SoftLayer API calls w/ response times

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#10]
Since Jumpgate will add one more layer on top of the SoftLayer API, latency and responsiveness is a concern of mine for the project. In the softlayer-python bindings there exists a TimedClient, which times each API call made using that client.

My idea for this feature is to used SoftLayer.TimedClient for API calls and report on API calls in an after hook if debugging is enabled. With that information, it will be a bit easier to determine how much of the Jumpgate response times are coming from the overhead of Jumpgate and the overhead of the calls to the SoftLayer API. It would also be good to have the entire request/response verb/path/headers/body available to debug both Jumpgate and potential bugs on the SoftLayer API side as well.

**Comment by amol** [comment]
Can you elaborate on this? I assume you mean just like OpenStack CLIs, when given with --debug flag gives all REST call it's making, we need to log SL requests sent for an OpenStack request received. Am I correct?

**Comment by sudorandom** [comment]
Sure. I updated the description inline.
