### ISSUE TITLE
Consider Starting Bare Metal/Ironic support

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#12]

**Comment by amol** [comment]
Should we consider writing a new SL driver (Ironic driver) interface over using PXE + IPMI? IMHO it would be better to provide new SL driver interface as, some of the PXE+IPMI parameters such as `ipmi_address` won't make sense in SL context and might confuse the user.

**Comment by sudorandom** [comment]
I agree. It's probably be more appropriate to add hardware support in the nova driver. When I made this I really wasn't sure if the purposes of the two APIs matched up.

**Comment by amol** [comment]
Would the following interface to SL Ironic driver be useful?

``` bash
ironic node-create --driver sl-driver \
    --driver_info cpu=4 \
    --driver_info domain=softlayer.com \
    --driver_info hostname=jumpgate \
    --driver_info memory=8 \
    --driver_info OS=Ubuntu \
    --driver_info hourly=true \
    --driver_info disk=100 \
    --driver_info disk=200 \
    --driver_info network=100Mbps \
    --driver_info vlan_public=3213 \
    --driver_info vlan_private=3144 
```

All of the parameters match the SL Python Client. Once provisioned user also gets IPMI address of the Baremetal from SL, which _may_ be used with PXE+IPMI Ironic driver. 

The above command will not create any baremetal instance, the ironic node-deploy will create one (node-deploy is not support by ironic CLI we will have execute http request)

``` bash
curl -i -X PUT -H "X-Auth-Token: $TOKEN" \
 -H 'Content-Type: application/json' \
 -H 'Accept: application/json' \
 -H 'User-Agent: python-ironicclient' \
 -d '{"target": "active"}' \
http://127.0.0.1:6385/v1/nodes/$NODE/states/provision
```

Not sure if we need to support `ironic port-*` commands as the instance will by default be getting network interface and an IP address. However, to add additional IP address these commands can be used.

``` bash
ironic port-create --node Node-UUID --extra subnet-id=3124 \
    --extra IP=ip_from_the_subnet
```

For this we will need to write Neutron Jumpgate driver though.

`ironic chassis-*` can be ignored for now as `chassis` is optional grouping mechanism
