### ISSUE TITLE
Tempest

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#140]
This is an issue to get tempest working again with Jumpgate. Several changes in tempest have caused tempest to no longer work with the current whitelist, example config and run_tempest_tests.py script.

This issue should address the following:
- Getting tempest to work again against jumpgate .
- Documenting what it takes to get tempest to work (environment, config values, etc)
- (optional) Create a SoftLayer-specific clean-up script that removes all SSH keys, images, VMs, volumes, etc. that were created from previous runs of the tempest tests. Certain test failures can leave around data which would build up over time in the current situation.
- (optional) Look into getting a set of tempest tests to run on each pull request. This will require setting API credentials in travis so secure environmental variables will probably have to be used: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables. Also, we need to verify that there's no way these credentials can leak into the resulting test logs.

**Comment by sudorandom** [comment]
Note: At the moment, the tempest takes quite a long time with Jumpgate, so plugging this into Travis-ci to happen every commit of a pull request is probably not wise until the . Running it daily or weekly would be better. This would then report the status through a web page or opening an issue on github.

**Comment by imkarrer** [comment]
I have created a pull request #141 to start addressing this issue.  Please review.
