### ISSUE TITLE
Jumpgate User Agent with the SoftLayer Client

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#148]
Currently, the user agent that Jumpgate emits when talking to SoftLayer's API is that of the SoftLayer bindings. This issue is to make the SoftLayer client in Jumpgate use a user agent specific to Jumpgate.

The work has already been done for softlayer-python to enabled custom user agents: https://github.com/softlayer/softlayer-python/pull/366

**Comment by zhiyanliu** [comment]
According to the upstream change [0] has been merged, I'd like to address this issue in jumpgate after that change get released with softlayer-python.

@sudorandom Do you think we could add a new option for user-agent in jumpgate like proxy config?

[0] https://github.com/softlayer/softlayer-python/commit/c926ec2fa23f6177f5a5e2004b637f160416d006
