### ISSUE TITLE
requirements.txt should include softlayer-python

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#19]
If you follow the install instructions for jumpgate (http://softlayer.github.io/jumpgate/get-started/) you still need to manually install the softlayer-python package (i.e. pip install softlayer). It seems this should be included in the requirements.txt rather than having the user manually determine its missing and have to install it separately.

**Comment by sudorandom** [comment]
This is resolved by 56b214fa5c90f1c5827b69254c5b3c1830520727
