### ISSUE TITLE
REST API support for GETting supported versions per service endpoint

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#20]
All of the OpenStack REST APIs I've worked with allow a REST API consumer to query they root URI (i.e. http://host:<port>/) to obtain information about the supported REST API versions for the endpoint.

For example in keystone paste ini: https://github.com/openstack/keystone/blob/master/etc/keystone-paste.ini#L85

The other services such as nova, cinder, etc. support this as well.

Although the openstack clients are smart enough to default the API version if a GET on the root URI is invalid/not implemented, it would be beneficial if the jumpgate compat layer returned a proper response here.

What you get with jumpgate right now is something like this:

```
WARNING:jumpgate.common.nyi:UNKNOWN PATH: GET /
INFO:jumpgate.common.hooks:GET /  501 Not Implemented [ReqId: req-daad5364-81f4-11e3-8654-0695fb7590bd]
127.0.0.1 - - [20/Jan/2014:11:03:59] "GET / HTTP/1.1" 501 95 "-" "python-requests/1.2.2 CPython/2.7.3 Linux/3.2.0-58-virtual"
INFO:gunicorn.access:127.0.0.1 - - [20/Jan/2014:11:03:59] "GET / HTTP/1.1" 501 95 "-" "python-requests/1.2.2 CPython/2.7.3 Linux/3.2.0-58-virtual"
```

Likely this is an enhancement.

**Comment by sudorandom** [comment]
I agree. By default, the identity driver is anchored to root, so an endpoint that responds similarly to public_version_api in keystone should respond to that request. I believe that was overlooked since it is not included in the reference docs here: http://api.openstack.org/api-ref-identity.html
