### ISSUE TITLE
identity support for validate token

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#22]
A number of the openstack components/CLIs expect to be able to validate a token using `GET /vX.Y/tokens/{tokenId}`. This is used when the consumer has a reference to an identity token, but they want to make sure it's still valid.. See: http://docs.openstack.org/api/openstack-identity-service/2.0/content/GET_validateToken_v2.0_tokens__tokenId__Token_Operations.html

Currently jumpgate does not support this route/service -- would be great if it could be added.

Likely an enhancement request.

**Comment by beittenc** [comment]
Jumpgate itself does support that endpoint: https://github.com/softlayer/jumpgate/blob/master/jumpgate/identity/__init__.py#L98

Are you specifically requesting that the SoftLayer driver be modified to attach to that endpoint?

**Comment by bodenr** [comment]
Yes I'm requesting that the SL driver support that endpoint.
