### ISSUE TITLE
Downgrading to Python 2.7

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#3]
Due to the current state of eventlet and gevent, it appears that the best deployment strategy at the moment (evented: http://docs.gunicorn.org/en/latest/design.html#choosing-a-worker-type) has to involve Python 2.7. However, Jumpgate currently exclusively works with Python 3.

I don't believe we're using too much that is exclusive to Python 3.3 currently. The biggest things that come to mind are:
- Not using `__init__.py` files
- Relative imports

Main libraries:
- Requests (Supports 2.6, 2.7, 3.3)
- SoftLayer bindings (Supports 2.6, 2.7, 3.3)
- Falcon (Supports 2.6, 2.7, 3.3)

**Comment by beittenc** [comment]
There are also some notes in the documentation that specifically reference Python 3.3, so we'll need to update that as well.

**Comment by sudorandom** [comment]
Finished.
