### ISSUE TITLE
basic identity admin_token support

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#35]
OpenStack keystone provides the notion of an `admin_token` which is effectively a shared secret between keystone and other openstack services. Many services integrating with keystone internally use the `admin_token` to make internal calls to keystone on behalf of the user - for example to validate a user token (ex see [here](https://github.com/openstack/trove/blob/master/etc/trove/api-paste.ini#L21)). For example see the keystone middleware which validates the `admin_token` in a request [here](https://github.com/openstack/keystone/blob/master/keystone/middleware/core.py#L69).

We need a similar notion in jumpgate in order to ease integration with openstack services using jumpgate. This jumpgate `admin_token` should permit authz to the jumpgate facing APIs -- it does not need to map into a SLAPI. For example, I should be able to validate a user (jumpgate based) token using the `GET /v2.0/tokens/{token_id}` API in jumpgate whereupon I can specify the admin_token secret key as my `X-Auth-Token` header and get into the jumpgate API to validate the token.

I will be submitting a PR in a min which implements this support and get your feedback.

**Comment by beittenc** [comment]
Resolved by #36
