### ISSUE TITLE
servers should have a user_id

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#39]
as per the nova server response, a server json should have a `server.user_id` which is the creator of the server (as I understand). See sample response here: [http://docs.openstack.org/api/openstack-compute/2/content/List_Servers-d1e2078.html](http://docs.openstack.org/api/openstack-compute/2/content/List_Servers-d1e2078.html)

Is this something we can get from the SLAPI?? If possible maybe jumpgate can just return the SL username as the `server.user_id`

**Comment by beittenc** [comment]
We actually have a user ID as well as a user name. I don't think there's any harm in doing that so we remain consistent with native OpenStack.

**Comment by sudorandom** [comment]
Here's the long, winding path to get the id of the user who created the CCI.

```
billingItem.orderItem.order.userRecordId
```

Example: https://gist.github.com/underscorephil/7882974

**Comment by bodenr** [comment]
@sudorandom this data is not currently exposed in the SL py client is it? just took a quick look but maybe I missed it.

**Comment by sudorandom** [comment]
Not easily. You would add what I added above to the mask for the API call. I.E.: https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/servers.py#L472

Then you'd be able to access it with `obj['billingItem']['orderItem']['order']['userRecordId']`, or, with using  lookup() (https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/utils.py#L21) `lookup(obj, 'billingItem', 'orderItem', 'order', 'userRecordId')`

**Comment by bodenr** [comment]
@sudorandom and @beittenc thanks for the tips. However at current I'm unable to get this working. I've tried various masks using both dotted notation as well as bracket notation. In all cases I can only get back the top level `billingItem` data. Admittedly I'm not that familiar with the SLAPI so likely I'm missing something basic here.

**Comment by beittenc** [comment]
@bodenr I think passing it in as a list like this should work, though I haven't tested yet.

mask=['billingItem', 'billingItem.orderItem', 'billingItem.orderItem.order', ''billingItem.orderItem.order.userRecordId']

**Comment by sudorandom** [comment]
@bodenr I think it's most likely a permissions issue. From my testing it looks like only the master user has access to see details  of an order item from a billing item. That seems really arbitrary to me but that's the behavior I see and I suspect it's intended.

**Comment by bodenr** [comment]
guys thanks for the prompt responses...

@sudorandom -- re permissions; so the master user is effectively the "account owner"... i.e. there is no way I can grant this permission to a standard account user?

my current thought is that I can code this up to try and get the user id, and if for some reason it can't be gotten the server response will contain a null `user_id`. Not the most glorious solution, but other properties are coming back null already.

so in `servers.py` add the mask:

``` python
        'modifyDate',
        'provisionDate',
        'sshKeys',
        'billingItem.orderItem.order.userRecordId',
    ]
```

and set the user_id in server response:

``` python
        'user_id': lookup(instance, 'billingItem', 'orderItem', 'order', 'userRecordId'),
        'updated': instance['modifyDate'],
        'image_name': image_name,
    }
```

thoughts on this approach?

what I really dislike is that I can't test the case where the user id can be fetched, but right now I don't have access to an account owner user id.

**Comment by bodenr** [comment]
fyi -- was able to get account owner id/key... the idea presented in my previous comment works and you will see the user_id if the user/key has proper auth... moving forward with change -- PR soon.

**Comment by bodenr** [comment]
implemented in https://github.com/softlayer/jumpgate/pull/42  ... closing
