### ISSUE TITLE
createImage is (extremely) blocking

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#4]
The issue here is that when Virtual_Guest::createArchiveTransaction is called, it returns a transaction instead of an empty blockdevicetemplategroup with an identifying global identifier. This is an issue because the call to create an image from a running server expects to get back a global identifier for the image which it can look up the status of, similarly to how CCIs are provisioned. Currently, SoftLayer's Jumpgate driver  waits for the entire capture during the createImage API call, which currently takes minutes.

After #3 is complete this is less of a problem, but this issue likely leads to usability issues on the part of tooling since one API call will sit on the line for minutes for the image capture to complete.

**Comment by beittenc** [comment]
Perhaps there are some API calls I haven't found that could be used to take the transaction ID and get back the GUID sooner. It would also make the entire process a bit less error prone since it currently relies upon some assumptions.
