### ISSUE TITLE
Add basic network support

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#5]
- Listing VLANs
- Listing Subnets.
- VLAN detail
- Subnet detail
- ???

There's a lot of discovery to do for this for the actual functionality. The [network manager](https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/network.py) is a good start as far as seeing what the SoftLayer API supports (and how) and, as always, the [API docs for OpenStack projects](http://api.openstack.org/api-ref-networking.html) is a good reference along with the quantum CLI client and, finally, tempest.

**Comment by beittenc** [comment]
The NetworkManager has a lot of code for interacting with the API, so this should just be a matter of figuring out how we want to add the support for OpenStack.

**Comment by rhodgin** [comment]
Can floating IP support please be included in this analysis? It isn't clear to me how the OpenStack APIs around floating IPs would be supported by the SoftLayer subnets and portable IPs but these APIs can be called automatically during instance creation.

**Comment by sudorandom** [comment]
@rhodgin +1 on that, sorry for the delay in response and movement on this.

I'm not sure how it will all map at the moment. I'm aware of **portable subnets** , which might map to floating ip pools (I'm not familiar enough with that concept) and **global ips** which are globally assignable ip addresses.

References:
- http://knowledgelayer.softlayer.com/articles/static-and-portable-ip-blocks
- http://knowledgelayer.softlayer.com/faq/what-global-ip

**Comment by mjfork** [comment]
Each of portable private subnets, portable public subnets, and global IPs are examples of floating IP pools, however they differ from OpenStack in that they have a limited scope they apply to (machines on the same VLAN).   In OpenStack, those IPs could be used anywhere.

**Comment by sudorandom** [comment]
(whoops in regard to closing this issue)

@mjfork Am I wrong in thinking that SoftLayer's global ips can be assigned to a machine on any VLAN? I just tested it out and it seems to be assignable to any device on the SoftLayer network.

**Comment by briancline** [comment]
Portables can't change the VLANs to which they point on the fly (maybe not
without a ticket anyway). Global IPs can, though.

**Comment by sudorandom** [comment]
Just more notes:
- SoftLayer's DNS API seems pretty matchable to the os-floating-ip-dns extension for nova v2 API - There doesn't seem like a nova v3 or neutron equivalent at the moment. I would have thought DNS would be managed via neutron. I'm probably missing something with this. http://developer.openstack.org/api-ref-compute-v2-ext.html#ext-os-floating-ip-dns

**Comment by jimlindeman** [comment]
For Openstack, DNS would be managed through the separate "Designate" project that is in StackForge.  https://github.com/stackforge/designate

**Comment by jimlindeman** [comment]
I think this can be closed out, addressed by issue #117 and #132 (once that's merged)
