### ISSUE TITLE
jumpgate requests fail with - unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#67]
With the introduction of SL client support for proxy in jumpgate (https://github.com/softlayer/jumpgate/pull/65) the out of the box jumpgate does not work due to a backleveled version of SL py client getting installed.

When you send a jumpgate request you'll get:

```
POST /v2.0/tokens  500 Internal Server Error [ReqId: req-b8f4e91e-b1cc-11e3-afe5-0676dee8c029]
127.0.0.1 - - [22/Mar/2014:09:17:38] "POST /v2.0/tokens HTTP/1.1" 500 101 "-" "python-novaclient"
Unexpected Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api.py", line 96, in __call__
    responder(req, resp, **params)  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_before
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_before
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_before
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 261, in do_before
    action(req, resp, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jumpgate-0.1-py2.7.egg/jumpgate/common/hooks/sl/client.py", line 10, in bind_client
    proxy=cfg.CONF['softlayer']['proxy'])
TypeError: __init__() got an unexpected keyword argument 'proxy'

```

The problem is that the softlayer py client installed via jumpgate's setup is backleveled and does not support the proxy kwarg.

If you install the softlayer py client from git hub manually (via git clone and then python install) the proxy kwargs is there.

I believe the solution here is to publish the latest version of sl py client to pypy or document in jumpgate that you need to install it manually.

**Comment by sudorandom** [comment]
Ah, I apologize for this. I completely overlooked this concern since I typically work off of master for both of these projects. I'll see about getting a minor release out for softlayer-python tomorrow since it's about time for it.

**Comment by bodenr** [comment]
@sudorandom  -- doesn't look like the latest softlayer py client got pushed to pypi yet https://pypi.python.org/pypi/SoftLayer  any idea when you plan to "submit" it?

**Comment by beittenc** [comment]
We want to get the CCI upgrade code merged in before we do the 3.1 release since it's close to finished.

**Comment by bodenr** [comment]
Note to work around this issue do the following:

```
cd /usr/local && sudo git clone https://github.com/softlayer/softlayer-python.git && cd /usr/local/softlayer-python && sudo pip install -r tools/requirements.txt && sudo python setup.py install
```

Now you can restart jumpgate and things should work:

```
sudo initctl restart jumpgate
```

**Comment by bodenr** [comment]
@sudorandom @beittenc -- we need to consider getting this one fixed.. A number of ppl are hitting it when trying out jumpgate. Thanks

**Comment by Neetuj** [comment]
I think i am hitting it too

Loading endpoint /network/v2.0/networks
Loading endpoint /network/v2.0/subnets
Loading endpoint /
Loading endpoint /network/v2.0/subnets
Loading endpoint /network/v2.0/subnets
Loading endpoint /v2.0/tokens
Loading endpoint /
Loading endpoint /
Loading endpoint /v2.0/tokens/{token_id}
Loading endpoint /v2.0/tokens
Loading endpoint /v2.0/tokens
Loading endpoint /v2.0/tokens/{token_id}/endpoints
Loading endpoint /v2.0/tokens/{token_id}
Loading endpoint /v2.0/tokens/{token_id}
Loading endpoint /v2.0/tenants
Loading endpoint /v2.0/tokens/{token_id}/endpoints
Loading endpoint /v2.0/tokens/{token_id}/endpoints
Loading endpoint /v2.0/tenants
Loading endpoint /v2.0/tenants
Unexpected Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 96, in
**call**
    responder(req, resp, *_params)  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
261, in do_before
    action(req, resp, kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/jumpgate-0.1-py2.7.egg/jumpgate/common/hooks/sl/client.py",
line 10, in bind_client
    proxy=cfg.CONF['softlayer']['proxy'])
TypeError: **init**() got an unexpected keyword argument 'proxy'
GET /  500 Internal Server Error [ReqId:
req-4ca061de-ba9c-11e3-960e-064923b0a07b]
127.0.0.1 - - [02/Apr/2014:14:23:41] "GET / HTTP/1.1" 500 101 "-"
"curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1
zlib/1.2.3.4libidn/1.23 librtmp/2.3"
Unexpected Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 96, in
**call**
    responder(req, resp, *_params)  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
262, in do_before
    responder(req, resp, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api_helpers.py", line
261, in do_before
    action(req, resp, kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/jumpgate-0.1-py2.7.egg/jumpgate/common/hooks/sl/client.py",
line 10, in bind_client
    proxy=cfg.CONF['softlayer']['proxy'])
TypeError: **init**() got an unexpected keyword argument 'proxy'
POST /v2.0/tokens  500 Internal Server Error [ReqId:
req-f4f43856-ba9c-11e3-8130-064923b0a07b]
127.0.0.1 - - [02/Apr/2014:14:28:23] "POST /v2.0/tokens HTTP/1.1" 500 101
"-" "python-novaclient"

**Comment by beittenc** [comment]
As a temporary workaround, installing the SoftLayer bindings from master will address this issue.

pip install git+http://github.com/softlayer/softlayer-python --upgrade

**Comment by bodenr** [comment]
@Neetuj  -- please see 2 comments back (above) -- I gave exact instructions on how to fix / workaround.

**Comment by lennonon** [comment]
My jumpgate works with your advice, thank you very much
