### ISSUE TITLE
Allow drivers to add extensions to the API to be displayed in extension API call

### ISSUE THREAD

**Issue by sudorandom** [softlayer/jumpgate#7]

**Comment by beittenc** [comment]
Could you elaborate more on what you're envisioning? This may be supportable already.

**Comment by sudorandom** [comment]
I'm actually not sure.

I think I was referring to how the extensions endpoint is hard-coded. I might have been thinking of making a general extension class(s) (to be mounted at `/v2/{tenant_id}/extensions` and `/v2/{tenant_id}/extensions/{alias}`) that any driver could use.

**Comment by sudorandom** [comment]
I may have also temporarily forgotten that extensions are service-specific. Nova has its own; keystone has its own. So we might just want to abandon this issue altogether.
