### ISSUE TITLE
support keystone services-list function

### ISSUE THREAD

**Issue by rhodgin** [softlayer/jumpgate#75]
Please consider adding support for the list services function in the identity APIs. Aspects of OpenStack code base use this function to determine what services can be used. The **init**.py file in jumpgate/identity/ indicates that would be supported:

``` python
# Service Catalog
disp.add_endpoint('v3_services', '/v3/services')
```

But when called it returns:
_Not Implemented (HTTP 501) (Request-ID: req-b2485312-b55a-11e3-a884-0654d7fc4b36)_

**Comment by jimlindeman** [comment]
I believe this was resolved with Issue #108
