### ISSUE TITLE
Add support for cinder block storage

### ISSUE THREAD

**Issue by rhodgin** [softlayer/jumpgate#76]
Please consider adding support in jumpgate for the OpenStack APIs/functionality around block storage. Specifically the APIs for listing, creating, getting details, and deleting volumes.

**Comment by amol** [comment]
This will be useful feature to add to jumpgate. However, we also have written a [Cinder Driver ](https://github.com/openstack/cinder/blob/master/doc/source/devref/drivers.rst) (not jumpgate drivers) for SL iSCSI (under code review), which is compatible with Havana release. This driver sits inside the Cinder service and allows user to create/use storage [along with local/other storage](https://wiki.openstack.org/wiki/Cinder-multi-backend).

**Comment by amol** [comment]
Once [iSCSI Manager](https://github.com/softlayer/softlayer-python/issues/282) (which we are working on) is completed then adding this feature would be simple.

**Comment by rhodgin** [comment]
Great, thanks for the update. When is the iSCSI Manager planned to be available?

**Comment by jimlindeman** [comment]
The currently supported block storage via Jumpgate is "portable storage" which supports attach/detech, but not attach at boot (via --block-device-mapping). 

FYI, the Cinder driver here:
https://github.com/softlayer/softlayer-cinder-driver
is intended for private Openstack deploys on top of Softlayer CCI/baremetal to utilize Softlayer's iSCSI (for a single account/datacenter) as the backend for its Cinder.

Is that enough info to close this out?

**Comment by sudorandom** [comment]
@jimlindeman yeah, I'd think so. I'll go ahead and close this. This can be re-opened until there's an objection.
