### ISSUE TITLE
URGENT: hashed flavor IDs break many things flavor releated

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#87]
With the latest jumpgate code from master, a number of functions are broken from a user perspective such as:
- `nova flavor-show`
- `nova boot`
- etc.

It appears the issue is rooted here: https://github.com/softlayer/jumpgate/commit/29e17a402d35cde37074bedfb1487a00fe30deb1

For example if you try to boot a server you'll end up with a jumgpate error like:

```
Unexpected Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api.py", line 96, in __call__
    responder(req, resp, **params)  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_befor
e
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_befor
e
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_befor
e
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 262, in do_befor
e
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 281, in do_after
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/falcon-0.1.8-py2.7.egg/falcon/api_helpers.py", line 281, in do_after
    responder(req, resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jumpgate-0.1-py2.7.egg/jumpgate/compute/drivers/sl/servers.py", line
 162, in on_post
    flavor_id = int(body['server'].get('flavorRef'))
ValueError: invalid literal for int() with base 10: 'MnZDUFU6MkdCcmFtOjEwMEdCOmxvY2Fs'
```

trying to show a flavor with nova also fails:

```
nova flavor-list
+----------------------------------+----------------------------------+-----------+------+-----------+------+-------+-------------+-----------+
| ID                               | Name                             | Memory_MB | Disk | Ephemeral | Swap | VCPUs | RXTX_Factor | Is_Public |
+----------------------------------+----------------------------------+-----------+------+-----------+------+-------+-------------+-----------+
| MXZDUFU6MUdCcmFtOjI1R0I6bG9jYWw= | 1 vCPU, 1024GB ram, 25GB, local  | 1024      | 25   | 0         |      | 1     | 1           | True      |
| MXZDUFU6MUdCcmFtOjEwMEdCOmxvY2Fs | 1 vCPU, 1024GB ram, 100GB, local | 1024      | 100  | 0         |      | 1     | 1           | True      |
| MnZDUFU6MkdCcmFtOjEwMEdCOmxvY2Fs | 2 vCPU, 2048GB ram, 100GB, local | 2048      | 100  | 0         |      | 2     | 1           | True      |
| NHZDUFU6NEdCcmFtOjEwMEdCOmxvY2Fs | 4 vCPU, 4096GB ram, 100GB, local | 4096      | 100  | 0         |      | 4     | 1           | True      |
| OHZDUFU6OEdCcmFtOjEwMEdCOmxvY2Fs | 8 vCPU, 8192GB ram, 100GB, local | 8192      | 100  | 0         |      | 8     | 1           | True      |
| MXZDUFU6MUdCcmFtOjI1R0I6U0FO     | 1 vCPU, 1024GB ram, 25GB, SAN    | 1024      | 25   | 0         |      | 1     | 1           | True      |
| MXZDUFU6MUdCcmFtOjEwMEdCOlNBTg== | 1 vCPU, 1024GB ram, 100GB, SAN   | 1024      | 100  | 0         |      | 1     | 1           | True      |
| MnZDUFU6MkdCcmFtOjEwMEdCOlNBTg== | 2 vCPU, 2048GB ram, 100GB, SAN   | 2048      | 100  | 0         |      | 2     | 1           | True      |
| NHZDUFU6NEdCcmFtOjEwMEdCOlNBTg== | 4 vCPU, 4096GB ram, 100GB, SAN   | 4096      | 100  | 0         |      | 4     | 1           | True      |
| OHZDUFU6OEdCcmFtOjEwMEdCOlNBTg== | 8 vCPU, 8192GB ram, 100GB, SAN   | 8192      | 100  | 0         |      | 8     | 1           | True      |
+----------------------------------+----------------------------------+-----------+------+-----------+------+-------+-------------+-----------+

nova flavor-show MXZDUFU6MUdCcmFtOjI1R0I6U0FO
ERROR (CommandError): No flavor with a name or ID of 'MXZDUFU6MUdCcmFtOjI1R0I6U0FO' exists.
```

Many of the openstack clients / tooling require the flavor ID to be integer parsable -- if not things start breaking. Therefore we need to keep flavor IDs as JSON ints over the wire.

**Comment by bodenr** [comment]
@Neetuj @sudorandom @beittenc as you can see in the above description, flavor IDs must remain int based otherwise many things break both on the client / consumer side as well as in jumpgate itself.

I would try to fix this one up, but it's not clear to me where you guys are going with these hashed IDs. Regardless this issue breaks a lot of function in jumpgate from a compute perspective and hence needs immediate attention IMO.

**Comment by Neetuj** [comment]
@bodenr sorry the whole flavors change got checked in by mistake..i will revert it and then get it reviewed and make sure none of the flavor related commands are broken .. 
I will talk to Nathan and Kevin about the hashed ID .. i thought this is what we wanted to do ..from the comments in issue #27

**Comment by sudorandom** [comment]
@bodenr @Neetuj I already reverted the change here: https://github.com/softlayer/jumpgate/commit/07dbbf0693cc721ac1b7d309ef6201d5cbe82c5d

The change wasn't 100% complete. @bodenr, I think you've pointed out the exact 2 places where the current implementation is lacking.

I'm closing this issue. Work on this will be continued in #27 and in the related pull request after it's made.

**Comment by bodenr** [comment]
@sudorandom  + @Neetuj  thanks.

regarding the flavor IDs being "int compatible"... based on the OpenStack API docs (http://api.openstack.org/api-ref-compute-v2.html) it does appear flavor IDs are strings and thus should not have to be compatible with something like `int(flavor.id)` but there are a few places in openstack consumer code that assumes they are.

therefore if you choose to use to use flavor ids which cannot be coherenced to int, we'll have to open defects on openstack proper projects to ensure compatibility with jumpgate.

**Comment by sudorandom** [comment]
@bodenr is there an example where there's consumer code which assumes that flavor id is an int? The that you pasted above is coming from `jumpgate/compute/drivers/sl/servers.py` which was making that assumption because that's an assumption that jumpgate was able to make for itself but I'm not aware of any OpenStack clients/projects that make this assumption as well.
