### ISSUE TITLE
Invalid image&network endpoints url in identity.templates

### ISSUE THREAD

**Issue by wpf710** [softlayer/jumpgate#89]
## current configuration for the image & network configurations in etc/identity.templates as below

catalog.RegionOne.image.name = Image Service
catalog.RegionOne.image.publicURL = http://localhost:5000/image/v2
catalog.RegionOne.image.privateURL = http://localhost:5000/image/v2
catalog.RegionOne.image.adminURL = http://localhost:5000/image/v2

catalog.RegionOne.network.name = Image Service
catalog.RegionOne.network.publicURL = http://localhost:5000/network/
catalog.RegionOne.network.privateURL = http://localhost:5000/network/
## catalog.RegionOne.network.adminURL = http://localhost:5000/network/

we need to remove the "/v2" for the Image Service URL and we need to change "network.name" and also remove the suffix "/" in the URL

I can provide the patch if it's valid.

**Comment by beittenc** [comment]
I'm not sure why all the image changes would be needed. We're targeting the v2 image API and those URLs work last we tested with the Glance CLI. What problems are you running into with images?:

**Comment by wpf710** [comment]
When I post tokens againt /v2.0/tokens,  it will return the service catalog based on those configurations, for example , 
{
    "endpoints": [{
        "adminURL": "http://localhost:5000/image/v2",
        "region": "RegionOne",
        "privateURL": "http://localhost:5000/image/v2",
        "publicURL": "http://localhost:5000/image/v2"
    }],
    "type": "image",
    "name": "Image Service",
    "endpoint_links": []
}

then I will regard the publicURL as the API context, and I know that I can all the /v2/images or /v1/images,  so the whole URL will be http://localhost:5000/image/v2/v1/images,  obviously Jumpgate will only listen on the /image/v1/images or /image/v2/images

for the nextwork,  when I trying to make Horizon work with Jumpgate,  it will complain that /nework//v2.0/extensions Not implemented(Which I'd implemented the extensions by returning empty list,  please notice that the double forward slash //, and if I remove the slash from the configuration file, then it will works.
