### ISSUE TITLE
glance image-list never returns but goes into endless loop

### ISSUE THREAD

**Issue by thomasspatzier** [softlayer/jumpgate#94]
I just did a 'glance image-list' with python-glanceclient against jumpgate with latest code from github. The CLI call never returned but seemed to have looped in jumpgate code. I re-occuring messages in the jumpgate worker log.

I did a 'glance index' as another test and that looped printing image formation of a set of images endlessly. Could it be that paging of the glance GET API is not handled correctly?

**Comment by sudorandom** [comment]
That's curious. I'll take a look at it. Thanks for submitting the issue.

**Comment by thomasspatzier** [comment]
Ok, thanks. Let me know if you need any information from me.

**Comment by sudorandom** [comment]
Yep, glance image-list uses the 'marker' parameter and the relevant call in Jumpgate doesn't respect that parameter yet.

I'll work on getting this issue fixed. `nova image-list` doesn't seem to have this issue.

**Comment by thomasspatzier** [comment]
Right, I can confirm that 'nova image-list' worded for me.
